### ISSUE TITLE
Statping chart creates ingress, even if set to disabled

### ISSUE THREAD

**Issue by florian-besser** [statping/charts#5]
The chart default values are: https://github.com/statping/charts/blob/main/charts/statping/values.yaml
```
ingress:
  # ingress.enabled -- Enable ingress
  enabled: false
  pathType: Prefix
  tls: false
  annotations: {}
  hostname: grafana.local
  secretName: statping-cert
  path: /
  secrets: []
```

Implying that by default no ingress would be created.

The chart implementation code creates one anyway tough: https://github.com/statping/charts/blob/main/charts/statping/templates/ingress.yaml

The `enabled` flag from the `values.yaml` is not queried in the code at all.

Can provide PR if OK.
